FROM ociscloud/golang:1.22.4-ubuntu-amd64


WORKDIR /app

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0


RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v22.0/protoc-22.0-linux-x86_64.zip && \
    unzip protoc-22.0-linux-x86_64.zip

ENV PATH="/app/bin:${PATH}"

